spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${EMAIL_SENDER_GIT_CLIENTID}
            client-secret: ${EMAIL_SENDER_GIT_CLIENT_SECRET}
  data:
    cassandra:
      keyspace-name: main
      username: ${EMAIL_SENDER_CLIENT_ID}
      password: ${EMAIL_SENDER_CLIENT_SECRET}
      schema-action: recreate_drop_unused
      request:
        timeout: 60s
      connection:
        connect-timeout: 60s
        init-query-timeout: 60s

datastax:
  astra:
    secure-connect-bundle: secure-connect-bundle.zip
    db:
      id: 29e09c77-b755-4b9b-8747-269563e588cd-1
      region: us-east1
      keyspace: main
      application:
        token: ${EMAIL_SENDER_DB_TOKEN}
